---
- hosts: all
  connection: local
  gather_facts: no
  # Collection モジュールの読み込み
  collections:
    - fragmentedpacket.netbox_modules

  vars:
    ansible_python_interpreter: ~/pyenv/bin/python

  # オブジェクト定義ファイルの読み込み
  vars_files:
    - roles/netbox/vars/object_vars.yml

  tasks:
    #- include_role: 
    #    name: netbox

    - name: region
      netbox_region:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ region }}"
          
    - name: site
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          region: "{{ region }}"
          name: "{{ site }}"

    # manufacturer 追加
    - name: add manufacturers
      netbox_manufacturer:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
      loop: "{{ manufactures }}"
    
    # device role 追加
    - name: add device role
      netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          slug: "{{ item.slug }}"
          color: "{{ item.color }}"
          # vm_role: true
      loop: "{{ device_roles }}"
    
    # device type 追加
    - name: add device types
      netbox_device_type:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          model: "{{ item.model }}"
          slug: "{{ item.slug }}"
          manufacturer: "{{ item.manufacturer }}"
          # vm_role: true
      loop: "{{ device_types }}"
    
    - name: cat1
      netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: catalyst11
          device_type: Catalyst
          device_role: core
          site: Shinjyuku

    - meta: end_play

    # device 追加
    - name: add devices
      netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          device_type: "{{ item.device_type }}"
          device_role: "{{ item.device_role }}"
          site: "{{ item.site }}"
      loop: "{{ devices }}"
      ignore_errors: yes
    
    # device に interface 追加 
    - name: add management interfaces
      netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          device: "{{ item.name }}"
          name: "{{ item.management.interface }}"
      loop: "{{ devices }}"
    
    # device interface に IP addresses 割り当て
    - name: assign ip addresses
      netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          interface:
            device: "{{ item.name }}"
            name: "{{ item.management.interface }}"
          address: "{{ item.management.address }}"
      loop: "{{ devices }}"
    
    # Primary adderss を選出
    - name: elect primary addresses
      netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          primary_ip4: "{{ item.management.address }}"
      loop: "{{ devices }}"
      ignore_errors: yes

    - name: Create Rack
      netbox_rack:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          rack_role: "{{ item.rack_role }}"
      loop: "{{ rack }}"
